### ISSUE TITLE
Tags and Subtags won't be displayed if they are written in uppercase letters

### ISSUE THREAD

**Issue by Cantolla** [Aidurber/tag-page-preview#10]
Hello,

Much like the issue (notes containing sub-tags cannot be displayed #9) the same happens to me, I'm on the latest version (0.0.11) and subtags won't be displayed, even if you change the scope, nothing happens, no tags will be shown.

This is true for edit and preview mode.

I think the issue is with uppercase, I tried several tags to test this and individual or nested tags work with lowercase, but stopped working when it was uppercase even if it was not a nested tag. 

This is a big issue for me as all of my tags are in uppercase letters.

**Comment by Aidurber** [comment]
Hi @Cantolla this should be fixed in version 0.0.12

You were absolutely right about the casing.
